name: CI/CD Build Docker MLflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'


    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn numpy


    - name: Train Model using MLflow Run
      run: |
        cd MLProject
        mlflow run . --env-manager=local --experiment-name CI_CD_Experiment


    - name: Read Run ID
      id: get_run_id
      run: |
        cd MLProject
        # Pastikan modelling.py kamu membuat file run_id.txt
        run_id=$(cat run_id.txt)
        echo "Detected Run ID: $run_id"
        echo "run_id=$run_id" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      env:
  
        MLFLOW_TRACKING_URI: file:./MLProject/mlruns
      run: |
        RUN_ID=${{ steps.get_run_id.outputs.run_id }}
        DOCKER_USER=${{ secrets.DOCKER_USERNAME }}
        IMAGE_NAME=churn-model-chesy
        
        echo "Building Docker Image for Run ID: $RUN_ID"
        
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model" \
          --name "$DOCKER_USER/$IMAGE_NAME:latest" \
          --enable-mlserver

        docker push "$DOCKER_USER/$IMAGE_NAME:latest"
